### ISSUE TITLE
Does ${cf:} reference also returns an error like Fn::ImportValue?

### ISSUE THREAD

**Issue by micropole** [MikeSouza/serverless-import-apigateway#2]
Hello,

I'm sorry if the question is a bit shortsighted. I haven't tested out what I'm going to suggest and sadly won't be able to for at least a week, so I prefer to post here as a theoretical discussion.

I'm currently working on a project searching to achieve just what your plugin is for: two Serverless stacks: one with javascript functions, one with python functions, and one API Gateway over both. I was looking for documentation on the topic and stumbled upon your Git.

So here is my question:

According to [Serverless documentation](https://serverless.com/framework/docs/providers/aws/events/apigateway/#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources), you can declare an API Gateway then export the necessary IDs through the outputs:

````
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2

resources:
  Resources:
    MyApiGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MyApiGW

Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: MyApiGW
      Export:
        Name: MyApiGateway-restApiId 

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - MyApiGW
          - RootResourceId
      Export:
        Name: MyApiGateway-rootResourceId
````

And then use `Fn::ImportValue` to reference it in your other stack

````
provider:
  apiGateway:
    restApiId:
      'Fn::ImportValue': MyApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': MyApiGateway-rootResourceId
````

You say that `Fn::ImportValue` returns an error, but wouldn't using `${cf:MyApiGateway.restApiId}` work? The code would be

````
provider:
  apiGateway:
    restApiId:
      ${cf:MyApiGateway.restApiId}
    restApiRootResourceId:
      ${cf:MyApiGateway.rootResourceId}
````

I'm asking because I'm using `${cf:}` to add the lambda function inside a secure VPC and I never had any trouble. Again, this is theoretical has I haven't tested out either solutions, I'm just trying to save me some time next week by doing things that are doomed to fail.

Thanks for your time!

**Comment by tomaszdudek7** [comment]
Well, the plugin is from 2017. Right now (in 2020 but probably earlier as well) it is indeed possible to use a CFN import in `provider` section.

Basically, an outdated repo and plugin. :P
